### ISSUE TITLE
Emit Remaining {Item.Count} when Recycle Executes

### ISSUE THREAD

**Issue by sh4t** [Sen66/PokemonGo-Bot#11]
Client.cs:433

Whenever the recycler runs, emit the remaining count of item(s) recycled, eg:

Recycled 3x Pokeball, 297 Pokeballs remaining..

..etc

**Comment by Sen66** [comment]
Is this really needed?
In the Settings.cs you define how many items of a specific type should remain(minimum)
It would also output the same value as remaining then.

**Comment by sh4t** [comment]
This is true and I was thinking about that as I typed it.  It was actually more of a "is this really throwing this many items away.." but wontfix is reasonable..

Perhaps adding some additional logic to the recycle; where-as it won't recycle Pokeballs over Revives if there is room in bag.

or it won't recycle Pokeballs even if you're over the count, if you have way more Potions.. just thinking out loud at this point :)

**Comment by 0x1911** [comment]
As a first step i would suggest to only recycle items if our backpack is full.

**Comment by Sen66** [comment]
closed due not needed.
