### ISSUE TITLE
Avoiding Magikarps?

### ISSUE THREAD

**Issue by arfianadam** [Sen66/PokemonGo-Bot#12]
I used https://github.com/DetectiveSquirrel/Pokemon-Go-Rocket-API before and I noticed that yours has a lot in common, in fact I thought that you pretty much forked it and modified it. But in DetectiveSquirrel's version, the bot keeps avoiding catching Magikarps. How do I know this? I was in a place where there were tons of magikarps and the bot only caught one magikarp in 5~10 minutes. I looked into the code and couldn't find anything. Do you have explanation of this issue? I'm sure a lot of people were experiencing this as well. Thanks

**Comment by sh4t** [comment]
i caught 291 magikarp today...

**Comment by Sen66** [comment]
Bot is not avoiding anything. Answered.
