### ISSUE TITLE
Idk whats going on i keep getting error

### ISSUE THREAD

**Issue by illdemoteu** [Sen66/PokemonGo-Bot#13]
Visual Studio cannot start debugging because the debug target 'C:\Users\user\Downloads\PokemonGo-Bot-master\PokemonGo\RocketAPI\Console\bin\Debug\PokemonGo.RocketAPI.Console.exe' is missing. Please build the project and retry, or set the OutputPath and AssemblyName properties appropriately to point at the correct location for the target assembly. and or the cmd opens and says press any key to continue and closes as soon as i do so

**Comment by alucard0134** [comment]
try just building it

**Comment by illdemoteu** [comment]
i have :/

**Comment by illdemoteu** [comment]
anything else that might work?

**Comment by millbj92** [comment]
Did you set the .Console project as the startup project?

**Comment by illdemoteu** [comment]
yea

**Comment by iN3x0R** [comment]
Follow my steps: 

- Download "Manage Nugets"  https://visualstudiogallery.msdn.microsoft.com/27077b70-9dad-4c64-adcf-c7cf6bc9970c 
- Open your ROCKET API in visual studio right click on the full projet and click "Restore Nuget Packages" when done build it again and its should be fixed. 

https://github.com/DetectiveSquirrel/Pokemon-Go-Rocket-API/issues/42 here is my topics who had the same problems as you.

Hope it helps:)

**Comment by Sen66** [comment]
3days ago. Should be fixed I guess.
