### ISSUE TITLE
LANGUAGE SERVER IS OFFLINE - PLEASE USE ENGLISH INSTEAD GERMAN

### ISSUE THREAD

**Issue by Sen66** [Sen66/PokemonGo-Bot#18]
title

**Comment by reuscam** [comment]
Just a note, it looked like the code does a translation lookup on every ?recycle?  Seems like it would be faster to cache all translations once, and then do a local lookup from a map.  Not sure if I am remembering correctly or not.

**Comment by Sen66** [comment]
You are right, it looks up the Pokemon name every time it needs it. A local translation is coming asap. Havent realy got to do do anything today. Had a headache and couldnt cencentrate on the bot and on my other peojects =/

**Comment by Sen66** [comment]
@reuscam fixed it. Now local translations.
