### ISSUE TITLE
Execute against specific config?

### ISSUE THREAD

**Issue by sh4t** [Sen66/PokemonGo-Bot#2]
@Sen66 could you have switch/flag that allows to specify a configuration file with settings to overwrite what is taken in during build from app.config; that way when executing you could just have different .xml files with the various location(s) you want to farm and the respective pokemon to skip/evolve/transfer etc.

This, versus modifying and re-building all the time.

**Comment by sh4t** [comment]
When you build and run (Ctrl F5) it produces an error dialog:

<img width="573" alt="screen shot 2016-07-22 at 4 25 50 pm" src="https://cloud.githubusercontent.com/assets/6337092/17073812/0528fd50-5029-11e6-8c1a-012876fca6a5.png">

**Comment by Sen66** [comment]
Rightclick on **PokemonGo.RocketAPI.Console**
Then click on **Set as Startup Project**

**Comment by sh4t** [comment]
I'll write this up as a secondary issue; you can close this issue out and I'll add a new one for the specific configuration files.
