### ISSUE TITLE
[Suggestion] Working together?

### ISSUE THREAD

**Issue by Zeift** [Sen66/PokemonGo-Bot#22]
Possible to work tgt w this source?
He have a working GUI in place now.

https://github.com/Panthere/GoBot

**Comment by Sen66** [comment]
I already done some work on my GUI and I already have a "template" in my head how I want it to look like. It is nice to have many other people on github making other GUI's and stuff. Im trying to do my best.

**Comment by dbfy** [comment]
Oh Look another clones of the originals. Sigh.
