### ISSUE TITLE
feature request (catch only specific)

### ISSUE THREAD

**Issue by S1NTET1C** [Sen66/PokemonGo-Bot#23]
catch only specific  pokemons

**Comment by Sen66** [comment]
This is something I could do really quick. Lemme see if I can commit it soon.

**Comment by Sen66** [comment]
You want it to only catch Rattatas for example, right? You can define pokemon you want to catch only.
You need to turn the filter in the settings on and define pokemon you want to catch in Program.cs Line 216. Ill move that stuff into the Application Config later.
![2016-07-24at19-19-19](https://cloud.githubusercontent.com/assets/5496231/17085226/8c827f28-51d3-11e6-8136-d6865eb2009c.jpg)
