### ISSUE TITLE
Feature request - Distance walked or msg when hatching

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#24]
Hey @Sen66 
Is there anyway you could add a message for when a egg is hatched ( when the pokemon comes out of the egg ) or if you could make it so it shows how far your character has walked since the time you started it?

So I can see when my egg's are hatched or how far I've walked?

It would be the best for the message option ofcourse so I know when to put new eggs into the thingy.

Looking forward for your response.

**Comment by Sen66** [comment]
Yes this is possible.

**Comment by Sen66** [comment]
I should be able to output it when an egg is hatched. Ill implement it soon.

**Comment by Lynical** [comment]
Thanks <3 please keep me up 2 date with this as I really need it

**Comment by Sen66** [comment]
This is a bit weird. I dump my whole inventory and have 2 incubators but on the dump I just find 1.
I probably only commit an update with the walked distance the current session.

**Comment by Lynical** [comment]
So it won't work with the messaging :(?
