### ISSUE TITLE
I can't seem to run the newest build.

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#25]
I'm getting a error which is: http://imgur.com/a/HDChS

@Sen66 can you please help me out here ;s

**Comment by Sen66** [comment]
Add `bool EggHatchedOutput { get; }`
to ISettings.cs, Ill commit it asap.

**Comment by Lynical** [comment]
http://imgur.com/a/PAagy

this is what happens atfer that. @Sen66

**Comment by Sen66** [comment]
cant see the full error. btw ill push out an update in ~1minute

**Comment by Lynical** [comment]
Please reply here as soon you release it so i'll show you right after if i still have errors or not.

**Comment by Sen66** [comment]
released

**Comment by Lynical** [comment]
http://imgur.com/a/85sON

error

**Comment by Sen66** [comment]
Rightclick on PokemonGO.RocketAPI.Console and set as startup project

**Comment by Lynical** [comment]
and the second error is this one: http://imgur.com/a/EYAbf

**Comment by Lynical** [comment]
I did that and now I have 3 errors

**Comment by Lynical** [comment]
http://imgur.com/a/Jp9SV

**Comment by Sen66** [comment]
But the errors from the GUI shouldnt affect your Console output?

**Comment by Lynical** [comment]
Don't ask me, I don't know anything about this whole thing I'm just doing what you're saying and this is what it's giving me ;s

**Comment by Lynical** [comment]
Do you know how to fix these?

**Comment by Lynical** [comment]
@Sen66

**Comment by Sen66** [comment]
If you dont want to compile it you can just download my release. Its precompiled and you can just edit the config file.
https://github.com/Sen66/PokemonGo-Bot/releases/tag/v1.2.3.0

**Comment by Lynical** [comment]
I wanna compile it myself... I don't like precompiled ones

**Comment by Lynical** [comment]
Why can't you look into te errors as I'm most likely not the only one getting them?

**Comment by Sen66** [comment]
The picture isnt working somehow

**Comment by Lynical** [comment]
http://imgur.com/a/IUIyR
these are 3 of the errors in 1 pic ;)

**Comment by Lynical** [comment]
please let me know once you opened it so i can delete it

**Comment by Sen66** [comment]
Ah okay, it seems like the last error is the only error that stops you from compiling.
Lemme look how to fix it.

**Comment by Lynical** [comment]
I deleted the image, don't refresh yours now

**Comment by Sen66** [comment]
Ok I commited another update that deleted some signing stuff from the application. This should fix your error.

**Comment by 0x1911** [comment]
in RocketAPI.GUI.Settings are missing members:

something like this is needed:
```
public bool CatchOnlySpecific { get; }
public bool EggHatchedOutput { get; }
public string UseLuckyEggMode { get; }
```

Also in RocketAPI/GUI the properties directory as well as its content Settings.Designer.cs and Resources.Designer.cs seem to be missing.

**Comment by Sen66** [comment]
Yeah im not updating the GUI as frequent as the other 2 projects =/

**Comment by 0x1911** [comment]
Haha i want in no way to use the console. ;)

Just wanted to add it in here since ppl without any knowledge will keep moaning about why the build is not completing flawless.

**Comment by Lynical** [comment]
@sen77 what is the new GUI?

**Comment by Lynical** [comment]
@Sen66 for some reason when I use the console as startup project it works, but with the GUI one it gives me 2 errors, why can't i use the gui mode?

**Comment by Lynical** [comment]
Also the console isn't outputting the refreshtoken for google.

But I wanna use the GUI one too ;(

**Comment by 0x1911** [comment]
@Lynical : If you want to use the GUI, just copy Settings.cs from the Console project to the winform gui project. Adjust namespaces if/where needed.

**Comment by Lynical** [comment]
@0x1911 That doesn't help, it still gives me 2 errors.

**Comment by 0x1911** [comment]
@Lynical : Ya my bad. have just quoted Sen66 + added some more notes.
Doesnt work for me either that way.

Well you'll have to continue waiting if you want to use a WindowsForm. ;)

**Comment by Lynical** [comment]
@0x1911 Wise people said that being happy with what you're getting is better then complaining for something you aren't getting.

**Comment by Sen66** [comment]
Yeah I cant upload these 2 files. I try to fix this. Also it wont output the google token anymore. It puts it into the settings automatically.

**Comment by Lynical** [comment]
Oh nice.

I hope you can get the GUI fixed, but even not this is still great!

**Comment by spot88** [comment]
The project start up should still be Console even you have the Gui now right?

**Comment by 0x1911** [comment]
Have you tried moving these two files around in the project and doing a commit. Aftwards change the files back into \GUI\Properties\ commit and push?

Thats my ghetto way of fixing such weird behaviour. Before starting a logical aproach. :D

**Comment by Sen66** [comment]
To fix the GUI just rightclick the 2 missing files and "Exclude from project"

**Comment by Lynical** [comment]
@Sen66 On the console one it doesn't say 2x super ball or whatever when cycling but it says 

for example:
Reclycled 1x superball
Reclycled 1x superball

so it duplicates or it doesn't count in 1 line anymore.

**Comment by Lynical** [comment]
@Sen66 Excluding the files from the project makes it a bigger mess, doesn't solve it.

**Comment by Lynical** [comment]
@Sen66 it would be really awesome if you could make it so it automatically puts those eggs you have in an ecalcbration thingy when available so you won't have to go to your phone to manually do it Lmao

**Comment by Lynical** [comment]
@Sen66 can you make it ^ or nah?

**Comment by Lynical** [comment]
@Sen66 Seems like the hatched egg message doesn't work

**Comment by Sen66** [comment]
okay thanks for your response, its really weird on my main account I bot with which is lvl22 I dont have any eggs lol

**Comment by Lynical** [comment]
@Sen66 I have 9/9 eggs all the time on my main lul guess I'm lucky with where I'm botting hihi

**Comment by Sen66** [comment]
Using the eggs works perfect. Its using one when available.
