### ISSUE TITLE
Sen can you link me to newest bot?

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#3]
Can ya please link me to the newest bot?
I got confused now since i found one of 2 mins ago and one of 2 hours ago..

**Comment by millbj92** [comment]
It depends on which bot you want. There are like 400 forks of the original at the moment. If you want, from what I've seen to be the most popular, search for the user DetectiveSquirrel.

**Comment by Lynical** [comment]
man I never asked you to reply here, i want @Sen66 to reply

**Comment by Sen66** [comment]
I wont update my fork anymore I think. I opened my own repo now:
https://github.com/Sen66/PokemonGo-Bot

**Comment by Lynical** [comment]
@sen66 does this one contain the newest and best updates?

**Comment by millbj92** [comment]
Github is a OPEN source community.  Gtfo git if you don't know how it is used.

**Comment by Lynical** [comment]
@millbj92 Why don't you get the fuck out of here? I never asked you to reply here you little shit.

**Comment by Sen66** [comment]
@Lynical yes. If you open an issue Ill be looking into it.
@millbj92 DetectiveSquirrel's version has lots of bugs and doesnt get updated as often as many for example.

**Comment by Lynical** [comment]
@sen66 do you have skype by any chance?

**Comment by Sen66** [comment]
@Lynical yes I do, but im not using it. If you want something open an issue :)

**Comment by Lynical** [comment]
@sen66 well it would be nice if i could just privately message you instead of these nerds getting into the conversation and fucking it up.

**Comment by millbj92** [comment]
Oh, I don't use that repo, but have seen a lot activity out of it. Mostly because it has a direct link from Ownedcore.

**Comment by Sen66** [comment]
@millbj92 Detectiv actually has some features from me(from my fork). Im more often online than him and commit more updates than him.

**Comment by sh4t** [comment]
@Sen66 has numerous PRs against Detectiv's and malcore has some links up on ownedcore pointing back to detectiv, which is likely how people are working their way here.
