### ISSUE TITLE
Bot console is no longer working.

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#31]
It stops doing anything after it tells me my level and xp left until next level, further then that it doesn't do anything anymore.

Something fucked up with one of the last builds you made @Sen66

**Comment by Lynical** [comment]
Also seems like since #28 the bot is really slow.

**Comment by Lynical** [comment]
Newest version also gave me a Null reference error.

**Comment by sh4t** [comment]
I cloned and it worked without any issue.  Make sure you're setting the Console as the default startup project.

**Comment by sh4t** [comment]
In terms of performance there does not appear to be any impact.  The footprint has actually decreased and overall performance is better.  It is using 8MB less memory than it was previously and overall the performance on catches, pokestops, etc seems unchanged.  I don't have any evidence that the catches and such are unchanged but I have been logging catch, miss, flee rates and they're in the same mean as they were in previous builds.

**Comment by sh4t** [comment]
@Lynical you might check any sleeps that you find larger than you would like.  Other than RPC, sleep seems to be the primary cause of delay, intended delays between req/res.  I wouldn't suggest reducing them because hammering the pgo RPC endpoints won't do anyone any favors..

**Comment by Sen66** [comment]
There was actually a bug that prevented the bot from running. This is fixed now. And it cant really be slower as the changes made nothing slower in generel. Instead, it made everything slightly better as @sh4t already mentioned.
