### ISSUE TITLE
Make it find specific pokemon?

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#39]
Is it possible so the bot looks for the specific pokemon because when using a pokemon map and putting the location on the bot, it doesn't catch the right pokemon ;s

**Comment by Lynical** [comment]
Also I would like to say that the message: looking for update, unable to look for update now.. keeps popping up at the beginning of each session while there isn't a new build out yet.

**Comment by Lynical** [comment]
@Sen66

**Comment by 0x1911** [comment]
The "looking for update" loop will be fixed shortly.

How does this root issue differ from issue #36?

**Comment by Lynical** [comment]
@0x1911 
Because with that one it only allows your bot to catch those specific pokemon, with this function im suggesting right here is that it actually goes for that pokemon ( hunts it literally ) so basically if you put the bot in the right location(coords) of that pokemon where it spawned, it should go for it right away and try to catch it for you.

**Comment by Lynical** [comment]
I also got a Null reference error, some parameter can't be null it said in dutch tho.
@0x1911  @Sen66

**Comment by Sen66** [comment]
Ok, ill look at it shortly.

**Comment by Sen66** [comment]
@Lynical for null reference open a new issue with all details you got please.
Looking for specific pokemon? Already implemented a bit code for this to only catch specific ones. Going to extend it maybe tomorow.
