### ISSUE TITLE
Whitelist option for pokemons to not be transfered while using duplicate as transfertype

### ISSUE THREAD

**Issue by Lynical** [Sen66/PokemonGo-Bot#42]
So basically, if you use duplicate it'll transfer all the pokemons of the same kind of the lower levels and keep you the highest one from that type of pokemon, it would be really good to have a whitelist so it doesn't transfer that kind of pokemon at all so all the levels you get from it (different types of pokemon levels) it'll keep instead of transferring it, as I have a couple of pokemons from the same type but all different good levels and I don't want them to get transfered by mistake from the bot.

Could this be looked at please asap?

@Sen66

**Comment by Lynical** [comment]
Instead of opening more issues, I'd also like to say here that sometimes when a pokestop is found it doesn't say anything at all, like it shows a blue colored time stamp but nothing else then that is after it.
 ^^ Bug

**Comment by Lynical** [comment]
Wait I think this bug actually means that I got soft banned lmao -.-

**Comment by Sen66** [comment]
When a pokestops displays nothing, it means you got nothing. This doesnt mean you got softbanned. Pokestops have a cooldown, so when you visit a pokestop while it still has a cooldown you wont get anything.

**Comment by Lynical** [comment]
I got softbanned as I get kicked out of gyms when trying to battle and I get no reward when spinning it in real life... and it doesn't have any cooldowns lol

**Comment by Lynical** [comment]
@Sen66

**Comment by Sen66** [comment]
Pokestops have cooldowns. To remove your softban throw like 30pokeballs and you should be unbanned.

**Comment by Lynical** [comment]
What do you mean with throw? like trying to catch a pokemon throw or just delete 30 balls from my inventory? @Sen66

**Comment by Sen66** [comment]
Throw. Try to catch a pokemon. You can also run the bot for ~15minutes. The ban goes away by the time.

**Comment by Lynical** [comment]
Thanks. also what about the main purpose of this post, the main suggestion ( first post ) can you make that?

**Comment by Sen66** [comment]
Sure. Ill do that after playing some counterstrike :)

**Comment by Lynical** [comment]
Thanks :) I also have another suggestion on another post if you don't mind checking that one too :) ( catch only specific eggs and leave the other ones out )

**Comment by Lynical** [comment]
@Sen66 Have you done it yet, i need this really bad as im losing good pokemon now.

**Comment by Lynical** [comment]
Ugh rip, I was hoping for this to be added in today..

**Comment by Sen66** [comment]
Pushed out an update with a whitelist for duplicate mode.
