### ISSUE TITLE
Google sign in method doesn't work

### ISSUE THREAD

**Issue by xexhyper** [Sen66/PokemonGo-Bot#46]
In console or graphical form it says (Go to  and type in) it doesn't show the site or code. Any help?

**Comment by myo** [comment]
+1 i think niantic changed their oauth code thing (oauth doc is tl;dr) gonna get the latest apk to check

**Comment by myo** [comment]
https://cdn.discordapp.com/attachments/206065340579315712/208159243495276555/unknown.png

**Comment by Lynical** [comment]
Yeah seems like I'm having this too.

**Comment by reuscam** [comment]
My google account logs in fine without any issues.  My PTC accounts can't
login currently.

**Comment by Lynical** [comment]
@reuscam Don't post false statements..

It doesn't work, if your bot was already logged in back when it was working and you haven't changed your coordinates of location then yeah it does login, but as soon you change coordinates and you have to re-enter the google code, it won't tell you the google code neither the site.

**Comment by Lynical** [comment]
Seems like Google changed their authentication method? like Myo said.

**Comment by reuscam** [comment]
I'm posting exactly what's happening to me. My single Google acct already had a refresh token, and works. I restarted it one hour ago, no problems. My two ptc accounts do not work. And I cannot create a new working Google acct, so the pre existing refresh token must be the ticket on the Google side. Not sure what's going on on the ptc side. Server down?  Banned?

**Comment by myo** [comment]
using an old token works fine i used a 1day old one

**Comment by Sen66** [comment]
Yeah Google login is broken atm. Ill look into it and keep you updated.

**Comment by Sen66** [comment]
![2016-07-28at15-16-45](https://cloud.githubusercontent.com/assets/5496231/17213819/54b09854-54d6-11e6-9459-cfdf5ecd2159.jpg)
Still doing some more testing.

**Comment by Sen66** [comment]
fixed it. Please tell me if it works for you. Servers seem to be a bit under load so it can take some times get get a response.

**Comment by redsmartie** [comment]
[15:32:40] The Bot trys to login with your submitted method.
Not Handled Exception: CaptchaRequired
[15:32:41] The Bot trys to login with your submitted method.
Not Handled Exception: BadAuthentication

**Comment by redsmartie** [comment]
I had to enter my Goggle username and password into the App.config which I hadn't had to do previously but its now logged me in

**Comment by Sen66** [comment]
yeah now you have to enter your google user:pass

**Comment by Sen66** [comment]
fixed.
