### ISSUE TITLE
index ArgumentException

### ISSUE THREAD

**Issue by Phrex** [Sen66/PokemonGo-Bot#50]
I have no idea. Is it because Ninantic's servers are burning hard or whatever?

http://i.imgur.com/YLvEfVp.png

**Comment by xexhyper** [comment]
I got that too

**Comment by Phrex** [comment]
Do u have the newest version? I dont updated it yet to 1.3.1.0, im using 1.3.0.0

**Comment by Phrex** [comment]
http://pastebin.com/bfsDk0wa

Debug output.

**Comment by reuscam** [comment]
The server is returning an unexpected response on one of the initial messages. Something like {"unknown": 2}. Wondering if they're finally using the unknown block in the request. Wish I knew more about the protocol.

**Comment by Phrex** [comment]
@reuscam good to know, thanks. Then we can just wait for a fix.

**Comment by Sen66** [comment]
Actually the server blocks youre requests when you send them too fast. Im still doing sometesting then Ill push out an update.

**Comment by Sen66** [comment]
https://github.com/Sen66/PokemonGo-Bot/commit/2b4b138b49f26d9bf38c2c350391876523a06a24
