### ISSUE TITLE
Doesn't show what I get from a PokeStop? :O

### ISSUE THREAD

**Issue by CYCOABHI** [Sen66/PokemonGo-Bot#6]
Doesn't show what I get from a pokestop and it doesnt recycle ;( everythign else is good :D It shows i'm not getting any exp aswell.

**Comment by Sen66** [comment]
Do you have recycler enanbled and have a not full backpack?

**Comment by CYCOABHI** [comment]
Yeah, mb, I forgot to add the "-" for my longitude lmfao, im dumb. RIP 1 acc. However sometimes on my working acc it still doesn't show the items/exp. It shows it on some pokestops and it doesnt show on some :| It's also like that for your screenshot (https://raw.githubusercontent.com/Sen66/PokemonGo-Bot/master/screenshot.jpg). Doesn't show the items/exp for 1st and 2nd pokestop

**Comment by Sen66** [comment]
Yeah, when the pokestop doesnt give you XP nor items it wont output it. SImple as that :smiley:

**Comment by CYCOABHI** [comment]
Yeah, but how come it doesnt giveme anything? :0 Is it cuz it's purple (already looted it in the last 5 mins) or is it a glitch?

**Comment by Sen66** [comment]
purple (already looted it in the last 5 mins)?
Could you give me a screenshot of your console output within some minutes?

**Comment by CYCOABHI** [comment]
I mean like when it shows the Pokestop but it doesn't show that you got any exp or items, is it because you already collected items from the pokestop? Or what is the reason for it not giving any items/exp? It should always give exp even if your bag if full, but in this case my bag as tons of space aswell O_o.

http://i.imgur.com/VfluUt4.png

Notice how the first 2 pokestops don't give anything?

**Comment by sh4t** [comment]
It appears as though it is hitting a spot it believes *it can* get but received a "try again later"

**Comment by Sen66** [comment]
PokeStops have a cooldown. When you visit one while it has the cooldown it doesnt return you anything.

**Comment by CYCOABHI** [comment]
Ah thanks for the reply, that's all i needed =)
